# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2db00741eacac6a95caba294e3841cb94e58611deb6c0566184fb85037607c5f6890676a4a0e99d1a12ec6f2c3a3d762b468d883290144e0dee8c3707d87167e

test:
  secret_key_base: 8049d1417b01dc70e320953e049592df32e2b40c433def50d37d233d26560fa17c268cb10c92cc181668de1186e777698e513ad59b745a6566dd8e9cf27aec0d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
